
# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: poly-scheduler
  image: polystream/scheduler:v0.22.6
  namespace: kube-system
  replicaCount: 1

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["Polybind"]

global:  
   # queueSort is not indented under extensions 
   # as it needs to be globally enabled once. 
  queueSort: []
  extensions: 
    preFilter: [] 
    filter: [] 
    postFilter: [] 
    score: [] 
    permit: [] 
    reserve: [] 
    preBind: []
    bind: []
    postBind: ["Polybind"]
